project:
  type: book

book:
  title: "WILDS Contributor Guide"
  reader-mode: true
  bread-crumbs: false
  author:
    - Scott Chamberlain
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-branch: main
  repo-actions: [edit, issue]
  repo-url: https://github.com/getwilds/guide/
  chapters:
    - index.qmd
    - contributing.qmd
    - style.qmd
    - part: codereview.qmd
      chapters:
        - codereview-dasl.qmd
        - codereview-external.qmd
        - codereview-general.qmd
        - codereview-guidelines.qmd
    - packagedocs.qmd
    - maintenance.qmd
    - conventions.qmd
  site-url: https://getwilds.org/guide/

bibliography: references.bib

format:
  html:
    theme:
      light: [sandstone, light.scss]
      dark: [slate, dark.scss]
    fontsize: 1.2em
    link-external-newwindow: true
    code-overflow: wrap
